<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-MELBE6D" name="org.example.TestRunner.Runners" tests="12" failures="2" timestamp="2022-07-14T20:45:22 EET" time="123.097" errors="1">
  <testcase name="runScenario" time="7.005" classname="org.example.TestRunner.Runners">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at org.example.StepDefinitions.D06_homeSlidersStepDef.url_changedf_success(D06_homeSlidersStepDef.java:20)
at ✽.user get navigated to first item url(file:///C:/Users/pc/IdeaProjects/E-commerce/src/main/resources/features/F06_homeSliders.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="13.422" classname="org.example.TestRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="14.059" classname="org.example.TestRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="7.770" classname="org.example.TestRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="11.751" classname="org.example.TestRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="13.164" classname="org.example.TestRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="10.246" classname="org.example.TestRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="6.314" classname="org.example.TestRunner.Runners">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at org.example.StepDefinitions.D06_homeSlidersStepDef.url_changeds_success(D06_homeSlidersStepDef.java:32)
at ✽.user get navigated to item url(file:///C:/Users/pc/IdeaProjects/E-commerce/src/main/resources/features/F06_homeSliders.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="12.005" classname="org.example.TestRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="10.820" classname="org.example.TestRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="8.153" classname="org.example.TestRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="8.388" classname="org.example.TestRunner.Runners">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:659)
at java.util.ArrayList.get(ArrayList.java:435)
at org.example.StepDefinitions.D07_followUsStepDef.navigate_to_rss_success(D07_followUsStepDef.java:71)
at ✽.navigate correctly to rss page(file:///C:/Users/pc/IdeaProjects/E-commerce/src/main/resources/features/F07_followUs.feature:20)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- org.example.TestRunner.Runners -->
